### ISSUE TITLE
Show ERROR message for database service, but it does not used by xCAT 

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-extensions#28] opened 2018-06-14 02:52 UTC
If using one DB, not required to check other type of DB.

```
2018-06-13 22:44:27,026 - DEBUG - systemctl stop xcatd [Passed]
Failed to stop mariadb.service: Unit mariadb.service not loaded.
2018-06-13 22:44:30,044 - DEBUG - Retry 1 ... ...systemctl stop mariadb
Failed to stop mariadb.service: Unit mariadb.service not loaded.
2018-06-13 22:44:33,071 - DEBUG - Retry 2 ... ...systemctl stop mariadb
Failed to stop mariadb.service: Unit mariadb.service not loaded.
2018-06-13 22:44:33,095 - ERROR - systemctl stop mariadb [Failed]
2018-06-13 22:44:33,113 - DEBUG - systemctl stop postgresql [Passed]
```

The error level message only means something wrong there.

**Comment by neo954** [comment] 2018-06-14 03:12
I think this issue is a duplicate of issue #20

**Comment by bybai** [comment] 2018-06-14 06:44
a duplicate of issue #20, close this one first.

**Closed as completed** 2018-06-14 06:44 UTC
Labels: duplicate
